---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - xds.nebucloud.io
  resources:
  - listeners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xds.nebucloud.io
  resources:
  - listeners/finalizers
  verbs:
  - update
- apiGroups:
  - xds.nebucloud.io
  resources:
  - listeners/status
  verbs:
  - get
  - patch
  - update
